---
site_name: Hay Description Specification
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
